server:
  port: 8000

spring:
  application:
    name: phc-world-gateway
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
#  cloud:
#    gateway:
#      httpclient:
#        connect-timeout: 1000
#        response-timeout: 5s
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: 'http://localhost:3000'
#            allow-credentials: true
#            allowedHeaders: '*'
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - OPTIONS
#      routes:
#        - id: path_simple_hello
#          uri: http://localhost:8080
#          predicates:
#            - Path=/hello
#          filters:
#            - CustomFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, httpexchanges, busrefresh

route:
  user-api:
    v1:
      base-url: lb://USER-API-SERVICE
  board-api:
    v1:
      base-url: lb://BOARD-API-SERVICE
