server:
  port: 8000

spring:
  application:
    name: phc-world-gateway
  cloud:
    gateway:
      httpclient:
        connect-timeout: 1000
        response-timeout: 5s
#      default-filters:
#        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: 'http://localhost:3000'
#            allow-credentials: true
#            allowedHeaders: '*'
#            allowedMethods:
#              - GET
#              - POST
#              - PUT
#              - DELETE
#              - PATCH
#              - OPTIONS
#      routes:
#        - id: path_simple_hello
#          uri: http://localhost:8080
#          predicates:
#            - Path=/hello
#          filters:
#            - CustomFilter

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

route:
  user-api:
    v1:
      base-url: lb://USER-API-SERVICE
